[package]
name = "coffilhg/test"
version = "1.2.3"
registry = "https://github.com/upliftgames/wally-index"
realm = "dev"

[dependencies]
CoffeeObjects = "coffilhg/coffeeobjects@2.3.5"

[server-dependencies]

[dev-dependencies]